### ISSUE TITLE
Heruku Error

### ISSUE THREAD

**Issue by mikeyhodl** [New-dev0/TgTwitterBot#3]
INFO:pyrogram.crypto.aes:Using TgCrypto
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/app/.heroku/python/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/twitterbot/__main__.py", line 11, in <module>
    Client = Client(
  File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/client.py", line 207, in __init__
    self.api_id = int(api_id) if api_id else None
ValueError: invalid literal for int() with base 10: '9787f6e00433496a22a583a43744efcd\n'

**Comment by New-dev0** [comment]
You have filed API_HASH or any other cred in API_ID variable. Correct it

**Comment by mikeyhodl** [comment]
Yes I have filled everything even locally I keep getting the same error

**Comment by New-dev0** [comment]
> Yes I have filled everything even locally I keep getting the same error

You have filled Wrong Value in API_ID Var. That is what, error says.

**Comment by mikeyhodl** [comment]
ok let me correct it
